### ISSUE TITLE
Please explain in the README how to run tests

### ISSUE THREAD

**Issue by yurivict** [thliebig/openEMS#78] opened 2021-08-19 01:11 UTC

**Comment by thliebig** [comment] 2023-01-02 09:59
What do you mean with tests? Currently the only "test" is running all the Tutorials and see if they still produce the expected results...

**Comment by biergaizi** [comment] 2023-02-21 23:34
I think we can close this Issue as a duplicate of #106.

**Comment by luzpaz** [comment] 2023-11-01 19:02
...so packagers can test if the application works.

**Closed** 2024-04-01 10:08 UTC
